const CREATE_PROJECT = "CREATE_PROJECT";
const UPDATE_PROJECT = "UPDATE_PROJECT";
const GET_USER_PROJECTS = "GET_USER_PROJECTS";
const GET_SINGLE_PROJECT = "GET_SINGLE_PROJECT";
const DELETE_PROJECT = "DELETE_PROJECT";
module.exports = {
  CREATE_PROJECT,
  UPDATE_PROJECT,
  GET_USER_PROJECTS,
  GET_SINGLE_PROJECT,
  DELETE_PROJECT,
};
