const CREATE_TASKS = "CREATE_TASKS";
const GET_PROJECT_TASKS = "GET_PROJECT_TASKS";
const UPDATE_TASK = "UPDATE_TASK";
const FILTER_TASKS = "FILTER_TASKS";
module.exports = {
  CREATE_TASKS,
  GET_PROJECT_TASKS,
  UPDATE_TASK,
  FILTER_TASKS,
};
